import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Archive, Bell, BellOff, Menu, MessageCircle, Paperclip, Pin, Plus, Search, Send, Settings, Users, X } from 'lucide-react'
import { clientEnv } from '../env'
import { enablePushNotifications, updateNotificationFocus } from '../notifications'
import { SettingsPanel } from '../settings/SettingsPanel'
import { useChatStore, type ConversationEntry } from './store'

type User = { id: string; displayName: string; username: string }
const titleFor = (entry: ConversationEntry) => entry.conversation.title ?? (entry.participants.map((item) => item.displayName).join(', ') || 'Conversation')
const initials = (value: string) => value.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase()

export function ChatWorkspace({ user, onSignedOut }: { user: User; onSignedOut: () => void }) {
  const store = useChatStore(); const [draft, setDraft] = useState(''); const [query, setQuery] = useState(''); const [drawer, setDrawer] = useState(false); const [findOpen, setFindOpen] = useState(false); const [settingsOpen, setSettingsOpen] = useState(false); const [findError, setFindError] = useState(''); const [notice, setNotice] = useState('')
  const loadConversations = store.loadConversations
  useEffect(() => { void loadConversations() }, [loadConversations])
  useEffect(() => {
    const focused = document.visibilityState === 'visible' ? store.selectedId ?? null : null
    void updateNotificationFocus(focused).catch(() => undefined)
    const refresh = () => void updateNotificationFocus(document.visibilityState === 'visible' ? store.selectedId ?? null : null).catch(() => undefined)
    const receive = (event: MessageEvent<{ type?: string; payload?: { title?: string } }>) => { if (event.data?.type === 'quickchat:push') setNotice(`${event.data.payload?.title ?? 'Quickchat'} sent a new message`) }
    document.addEventListener('visibilitychange', refresh); navigator.serviceWorker?.addEventListener('message', receive)
    return () => { document.removeEventListener('visibilitychange', refresh); navigator.serviceWorker?.removeEventListener('message', receive); void updateNotificationFocus(null).catch(() => undefined) }
  }, [store.selectedId])
  const selected = store.conversations.find((entry) => entry.conversation.id === store.selectedId)
  const visible = useMemo(() => store.conversations.filter((entry) => !entry.membership.archivedAt && titleFor(entry).toLowerCase().includes(query.toLowerCase())), [store.conversations, query])
  const messages = store.selectedId ? store.messages[store.selectedId] ?? [] : []
  const send = (event: FormEvent) => { event.preventDefault(); if (draft.trim()) { void store.send(user.id, draft); setDraft('') } }
  const startDirect = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setFindError(''); const username = String(new FormData(event.currentTarget).get('username') ?? '')
    try { const found = await fetch(`${clientEnv.VITE_API_URL}/api/v1/users/lookup?username=${encodeURIComponent(username)}`, { credentials: 'include' }); const userData = await found.json(); if (!found.ok) throw new Error(userData.error?.message); const created = await fetch(`${clientEnv.VITE_API_URL}/api/v1/conversations/direct`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ userId: userData.user.id }) }); if (!created.ok) throw new Error('Unable to start conversation'); setFindOpen(false); await store.loadConversations() } catch (error) { setFindError(error instanceof Error ? error.message : 'User not found') }
  }
  return <div className="chat-workspace">
    <nav className="chat-rail"><span className="brand-icon"><MessageCircle size={20} /></span><button aria-label="Messages"><MessageCircle /></button><button aria-label="People"><Users /></button><button aria-label="Enable notifications" onClick={() => void enablePushNotifications().then(() => setNotice('Notifications enabled')).catch((error: unknown) => setNotice(error instanceof Error ? error.message : 'Unable to enable notifications'))}><Bell /></button><button aria-label="Settings" onClick={() => setSettingsOpen(true)}><Settings /></button><span className="fallback-avatar">{initials(user.displayName)}</span></nav>
    <aside className={`inbox ${drawer ? 'open' : ''}`}><header><div><small>Quickchat</small><h1>Messages</h1></div><button className="icon-button" onClick={() => setFindOpen(true)} aria-label="New conversation"><Plus /></button><button className="icon-button inbox-close" onClick={() => setDrawer(false)}><X /></button></header><label className="search-field"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search conversations" /></label>
      <div className="conversation-list">{store.loading && <p className="list-state">Loading conversations…</p>}{!store.loading && !visible.length && <div className="list-empty"><Users /><strong>No conversations</strong><p>Find someone by their exact username.</p><button className="secondary-button" onClick={() => setFindOpen(true)}>Start chatting</button></div>}{visible.map((entry) => <button className={`conversation-item ${store.selectedId === entry.conversation.id ? 'active' : ''}`} key={entry.conversation.id} onClick={() => { void store.select(entry.conversation.id); setDrawer(false) }}><span className="fallback-avatar">{initials(titleFor(entry))}</span><span><strong>{titleFor(entry)}</strong><small>{entry.conversation.type === 'group' ? `${entry.participants.length + 1} members` : entry.participants[0]?.username ? `@${entry.participants[0].username}` : 'Direct conversation'}</small></span>{entry.membership.pinnedAt && <Pin size={13} />}</button>)}</div>
    </aside>
    <main className="conversation-view">{selected ? <><header><button className="icon-button mobile-inbox" onClick={() => setDrawer(true)}><Menu /></button><span className="fallback-avatar">{initials(titleFor(selected))}</span><div><strong>{titleFor(selected)}</strong><small>{selected.conversation.type === 'group' ? 'Group conversation' : 'Private conversation'}</small></div><span className="header-spacer" /><button className="icon-button" onClick={() => void store.setInbox(selected.conversation.id, { pinned: !selected.membership.pinnedAt })}><Pin /></button><button className="icon-button" onClick={() => void store.setInbox(selected.conversation.id, { mutedUntil: selected.membership.mutedUntil ? null : new Date(Date.now() + 8 * 3600000).toISOString() })}><BellOff /></button><button className="icon-button" onClick={() => void store.setInbox(selected.conversation.id, { archived: true })}><Archive /></button></header><section className="message-list">{!messages.length && <div className="conversation-empty"><MessageCircle /><strong>No messages yet</strong><p>Say hello. Your message will appear on every signed-in device.</p></div>}{messages.map((message) => <article className={message.senderId === user.id ? 'mine' : ''} key={message.id}><p>{message.deletedForEveryoneAt ? 'This message was deleted' : message.body}</p><time>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}{message.editedAt ? ' · edited' : ''}</time></article>)}</section><form className="message-composer" onSubmit={send}><button type="button" aria-label="Attach file"><Paperclip /></button><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a message" maxLength={4000} /><button type="submit" aria-label="Send"><Send /></button></form></> : <div className="empty-chat"><span className="empty-chat-icon"><MessageCircle /></span><h1>Your messages live here</h1><p>Choose a conversation or start a private chat with an exact username.</p><button className="primary-button" onClick={() => setFindOpen(true)}>New conversation</button></div>}</main>
    {findOpen && <div className="modal-backdrop" onMouseDown={() => setFindOpen(false)}><form className="find-dialog" onSubmit={startDirect} onMouseDown={(event) => event.stopPropagation()}><header><div><small>New conversation</small><h2>Find by username</h2></div><button type="button" className="icon-button" onClick={() => setFindOpen(false)}><X /></button></header><label>Username<input name="username" autoFocus pattern="[A-Za-z0-9_]{3,32}" placeholder="exact_username" required /></label>{findError && <p role="alert">{findError}</p>}<button className="primary-button">Start conversation</button></form></div>}
    {settingsOpen && <SettingsPanel onClose={() => setSettingsOpen(false)} onSignedOut={onSignedOut} />}
    {store.error && <div className="app-toast">{store.error}<button onClick={() => useChatStore.setState({ error: undefined })}>Dismiss</button></div>}
    {notice && <div className="app-toast" role="status">{notice}<button onClick={() => setNotice('')}>Dismiss</button></div>}
  </div>
}
